# Generated by Django 5.0.2 on 2024-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickuplines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickupline', models.CharField(max_length=200)),
            ],
        ),
    ]
